version: '3.4'
services:
  mysql:
    image: mysql:latest
#    build:
#      context: SQL
#      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
      MYSQL_USER: recipeuser
      MYSQL_PASSWORD: testpassword123
      MYSQL_DATABASE: recipes
    volumes:
      - ./mysql_data:/var/lib/mysql
      #- ./SQL:/docker-entrypoint-initdb.d/:ro
  dynamodb:
    image: amazon/dynamodb-local:latest
    environment:
      DYNAMO_ACCESS_KEY: whatever
      DYNAMO_SECRET_KEY: whocares
      AWS_REGION: us-west-2
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/home/dynamodblocal
      - ./dynamo_data:/home/data
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/data"
  website:
    image: jannaloeffler/recipe_website:latest
    build:
     context: .
     dockerfile: ./Website/Dockerfile.dev
    depends_on:
      - recipeapi
      - mysql
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
#    secrets: Uncomment these secrets if you want to use Microsoft + FB Auth locally
#      - Authentication.Microsoft.ApplicationId
#      - Authentication.Microsoft.Password
#      - Facebook.API.Key
#      - Facebook.API.Secret
    ports:
     - "3000:80"
  recipeapi:
    image: jannaloeffler/recipeapi:latest
    #build:
    #  context: .
    #  dockerfile: ./RecipeAPI/Dockerfile.dev
    depends_on:
      - dynamodb
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      AWS_ACCESS_KEY_ID: 'whatever'
      AWS_SECRET_ACCESS_KEY: 'whocares'
    ports:
     - "8080:80"
     
volumes:
  dynamodata: {}
# Un-comment out these secrets if you want to use Microsoft + FB Auth locally  
#secrets:
#  Authentication.Microsoft.ApplicationId:
#    file: ~/.docker/secrets/Authentication.Microsoft.ApplicationId.txt
#  Authentication.Microsoft.Password:
#    file: ~/.docker/secrets/Authentication.Microsoft.Password.txt
#  Facebook.API.Key:
#    file: ~/.docker/secrets/Facebook.API.Key.txt
#  Facebook.API.Secret:
#    file: ~/.docker/secrets/Facebook.API.Secret.txt
