name: Deploy PR to Dev

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    types: [ labeled ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    pkg_dev:
      if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy_pr') }}
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: Docker Login
            uses: docker/login-action@v1.6.0
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                # Password or personal access token used to log against the Docker registry
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
     #     - name: Build
     #       env:
     #           TAG: dev
     #           #TAG: ${{ github.sha }}
     #       run: docker-compose -f RecipeApp/docker-compose.yml build
     #     - name: Push
     #       env:
     #           TAG: dev
     #           #TAG: ${{ github.sha }}
     #       run: docker-compose -f RecipeApp/docker-compose.yml push
          
          - name: Deploy UI to Azure
            uses: azure/webapps-deploy@v2
            with:
               app-name: 'recipe-ui'
               slot-name: 'qa'
               publish-profile: ${{ secrets.AzureAppService_PublishProfile_c95c7c71939a407eb1c8d2f3d7d3004f }}
               images: 'index.docker.io/queenofcode/recipe_website:dev'
        # NOTE: The API deploys in alternate way in Azure, for demo purposes
