name: Deploy PR to Dev

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    types: [ labeled ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    pkg_dev:
      if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy_pr') }}
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: Docker Login
            uses: docker/login-action@v1.6.0
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                # Password or personal access token used to log against the Docker registry
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Build
            env:
                TAG: dev
                #TAG: ${{ github.sha }}
            run: docker-compose -f RecipeApp/docker-compose.yml build
          - name: Push
            env:
                TAG: dev
                #TAG: ${{ github.sha }}
            run: docker-compose -f RecipeApp/docker-compose.yml push
          - name: Azure authentication
            uses: azure/login@v1
            with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
          - name: Deploy UI to Azure
            uses: azure/webapps-deploy@v2
            with:
               app-name: 'recipe-ui'
               slot-name: 'qa'
               images: 'index.docker.io/queenofcode/recipe_website:dev'
          - name: Deploy API to Azure
            uses: azure/webapps-deploy@v2
            with:
               app-name: 'recipe-dataapi'
               slot-name: 'qa'
               images: 'index.docker.io/queenofcode/recipeapi:dev'
    integration_test: 
      runs-on: ubuntu-latest
      if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy_pr') }}
      needs: pkg_dev
      steps:
        - uses: actions/checkout@v2
          with:
            # Disabling shallow clone is recommended for improving relevancy of reporting
            fetch-depth: 0
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.101
        - name: Install dependencies
          run: dotnet restore RecipeApp/Website.sln
        - name: Build
          run: dotnet build --configuration Release --no-restore RecipeApp/Website.sln
        - name: Test
          env:
             RecipeEnv: Production
             RECIPE-INTERNAL-AUTH: ${{ secrets.RECIPE-INTERNAL-AUTH }}
          run: dotnet test --no-restore --no-build --configuration Release --verbosity normal RecipeApp/Website.sln --filter Category==Integration
